/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uni_leipzig.informatik.asv.gephi.chinesewhispers;

import de.uni_leipzig.informatik.asv.gephi.chinesewhispers.ChineseWhispersClusterer.Propagation;

/**
 *
 * @author Jorg Bliesener
 */
public class ChineseWhispersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChineseWhispersPanel
     */
    public ChineseWhispersPanel() {
        initComponents();
    }
    
    public int getIterations() {
        return (Integer) jSpinnerIterations.getValue();
    }
    
    public void setIterations(int iterations) {
        jSpinnerIterations.setValue(iterations);
    }
    
    public boolean getDoColoring() {
        return jCheckBoxDoColoring.isSelected();
    }

    public void setDoColoring(boolean doColoring) {
        jCheckBoxDoColoring.setSelected(doColoring);
    }
    
    public boolean getRandomNodeOrder() {
        return jCheckBoxRandomNodeOrder.isSelected();
    }

    public void setRandomNodeOrder(boolean b) {
        jCheckBoxRandomNodeOrder.setSelected(b);
    }

    public ChineseWhispersClusterer.Propagation getPropagation() {
        return (ChineseWhispersClusterer.Propagation) jComboBoxPropagationType.getSelectedItem();
    }
    
    public void setPropagation(ChineseWhispersClusterer.Propagation item) {
        jComboBoxPropagationType.setSelectedItem(item);
        boolean enabled = item.equals(Propagation.VOTE);
        jLabel3.setEnabled(enabled);
        jSpinnerPropagationVoteValue.setEnabled(enabled);
    }

    public float getPropagationVoteValue() {
        return (Float) jSpinnerPropagationVoteValue.getValue();
    }
    
    public void setPropagationVoteValue(float propagationVoteValue) {
        jSpinnerPropagationVoteValue.setValue(propagationVoteValue);
    }
    
    public boolean getStepwiseUpdates() {
        return jCheckBoxStepwiseUpdates.isSelected();
    }
    
    public void setStepwiseUpdates(boolean stepwiseUpdates) {
        jCheckBoxStepwiseUpdates.setSelected(stepwiseUpdates);
    }
    
    public float getMinimumEdgeWeight() {
        return (Float) jFormattedTextFieldMinimumEdgeWeight.getValue();
    }
    
    public void setMiniumEdgeWeight(float minimumEdgeWeight) {
        jFormattedTextFieldMinimumEdgeWeight.setValue(minimumEdgeWeight);
    }
    
    public boolean getUseVisibleGraph() {
        return (jComboBoxClusterSource.getSelectedIndex()==1);
    }
    
    public void setUseVisibleGraph(boolean useVisibleGraph) {
        jComboBoxClusterSource.setSelectedIndex(useVisibleGraph ? 1 : 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new org.jdesktop.swingx.JXHeader();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerIterations = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxDoColoring = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxRandomNodeOrder = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxClusterSource = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPropagationType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerPropagationVoteValue = new javax.swing.JSpinner();
        jCheckBoxStepwiseUpdates = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldMinimumEdgeWeight = new javax.swing.JFormattedTextField();

        header.setDescription(org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.header.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jPanel1.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel1.text")); // NOI18N

        jSpinnerIterations.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxDoColoring, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jCheckBoxDoColoring.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxRandomNodeOrder, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jCheckBoxRandomNodeOrder.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel8.text")); // NOI18N

        jComboBoxClusterSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Complete graph", "Visible graph" }));
        jComboBoxClusterSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClusterSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxRandomNodeOrder))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jCheckBoxDoColoring))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxClusterSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxClusterSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBoxDoColoring))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBoxRandomNodeOrder))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jPanel2.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel2.text")); // NOI18N

        jComboBoxPropagationType.setModel(new org.jdesktop.swingx.combobox.EnumComboBoxModel(ChineseWhispersClusterer.Propagation.class));
        jComboBoxPropagationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPropagationTypeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel3.text")); // NOI18N

        jSpinnerPropagationVoteValue.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.1f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.01f)));
        jSpinnerPropagationVoteValue.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerPropagationVoteValue, "0.00"));

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxStepwiseUpdates, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jCheckBoxStepwiseUpdates.text")); // NOI18N
        jCheckBoxStepwiseUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStepwiseUpdatesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jLabel6.text")); // NOI18N

        jFormattedTextFieldMinimumEdgeWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldMinimumEdgeWeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jFormattedTextFieldMinimumEdgeWeight.setText(org.openide.util.NbBundle.getMessage(ChineseWhispersPanel.class, "ChineseWhispersPanel.jFormattedTextFieldMinimumEdgeWeight.text")); // NOI18N
        jFormattedTextFieldMinimumEdgeWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMinimumEdgeWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldMinimumEdgeWeight)
                    .addComponent(jCheckBoxStepwiseUpdates)
                    .addComponent(jComboBoxPropagationType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerPropagationVoteValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPropagationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerPropagationVoteValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBoxStepwiseUpdates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldMinimumEdgeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxStepwiseUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStepwiseUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxStepwiseUpdatesActionPerformed

    private void jFormattedTextFieldMinimumEdgeWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMinimumEdgeWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldMinimumEdgeWeightActionPerformed

    private void jComboBoxPropagationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPropagationTypeActionPerformed
        boolean enable = getPropagation() == ChineseWhispersClusterer.Propagation.VOTE;
        jSpinnerPropagationVoteValue.setEnabled(enable);
        jLabel3.setEnabled(enable);
    }//GEN-LAST:event_jComboBoxPropagationTypeActionPerformed

    private void jComboBoxClusterSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClusterSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClusterSourceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JCheckBox jCheckBoxDoColoring;
    private javax.swing.JCheckBox jCheckBoxRandomNodeOrder;
    private javax.swing.JCheckBox jCheckBoxStepwiseUpdates;
    private javax.swing.JComboBox jComboBoxClusterSource;
    private javax.swing.JComboBox jComboBoxPropagationType;
    private javax.swing.JFormattedTextField jFormattedTextFieldMinimumEdgeWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerIterations;
    private javax.swing.JSpinner jSpinnerPropagationVoteValue;
    // End of variables declaration//GEN-END:variables
}
